// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"userSystem/service/user/rpc/internal/logic"
	"userSystem/service/user/rpc/internal/svc"
	"userSystem/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateRequest) (*user.Response, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *user.UpdateRequest) (*user.Response, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}
